# Generated by Django 2.1.4 on 2019-01-10 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('em_id', models.CharField(max_length=50, unique=True)),
                ('em_create_date', models.DateTimeField(verbose_name='date published')),
                ('em_code', models.CharField(max_length=50, unique=True)),
                ('em_name', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='GiaoDich',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gd_id', models.CharField(max_length=200, unique=True)),
                ('create_date', models.DateTimeField(verbose_name='date published')),
                ('status', models.CharField(max_length=2)),
                ('from_serial', models.CharField(max_length=200)),
                ('to_serial', models.CharField(max_length=200)),
                ('em_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PagesApp.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='GiaoDichDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gd_detail_id', models.CharField(max_length=200, unique=True)),
                ('create_date', models.DateTimeField(verbose_name='date created')),
                ('serial', models.CharField(max_length=200)),
                ('note', models.CharField(max_length=250)),
                ('em_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PagesApp.Employee')),
                ('gd_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PagesApp.GiaoDich')),
            ],
        ),
        migrations.CreateModel(
            name='TrangThaiSim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_id', models.CharField(max_length=50, unique=True)),
                ('status_name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='giaodichdetail',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PagesApp.TrangThaiSim'),
        ),
    ]
