# Generated by Django 2.1.4 on 2019-01-10 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PagesApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='em_id',
        ),
        migrations.RemoveField(
            model_name='giaodich',
            name='gd_id',
        ),
        migrations.RemoveField(
            model_name='giaodichdetail',
            name='gd_detail_id',
        ),
        migrations.RemoveField(
            model_name='trangthaisim',
            name='status_id',
        ),
    ]
