# Generated by Django 2.1.4 on 2019-01-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PagesApp', '0002_auto_20190110_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='em_create_date',
            field=models.DateTimeField(verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.SmallIntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='giaodich',
            name='from_serial',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='giaodich',
            name='status',
            field=models.SmallIntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='giaodich',
            name='to_serial',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='giaodichdetail',
            name='serial',
            field=models.BigIntegerField(),
        ),
    ]
