# Generated by Django 2.1.4 on 2019-01-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PagesApp', '0003_auto_20190110_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='em_create_date',
            field=models.DateField(verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='giaodich',
            name='create_date',
            field=models.DateField(verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='giaodichdetail',
            name='create_date',
            field=models.DateField(verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='giaodichdetail',
            name='status',
            field=models.SmallIntegerField(max_length=2),
        ),
        migrations.DeleteModel(
            name='TrangThaiSim',
        ),
    ]
